---
name: check-script

on:
  pull_request:

jobs:
  check_run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y luajit
      - run: luajit rename.lua bones_new/
      - run: git diff --ignore-all-space -- bones_new/
