---
name: do-rename
on:
  push:
  pull_request:

jobs:
  run_rename_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y luajit
      - run: luajit rename.lua bones_new/
      - run: git diff
