---
name: do-rename

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run_rename_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y luajit
      - run: luajit rename.lua bones_new/
      - run: |
          if ! git diff --exit-code -- bones_new/ >/dev/null; then
            echo "Committing renames"
            git config --global user.name 'Automated Rename'
            git config --global user.email 'automated+rename@example.com'
            git add -u && git commit -am "Apply wand names" && git push
          fi
